apiVersion: apps/v1
kind: Deployment
metadata:
  name: telecom-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: telecom-api
  template:
    metadata:
      labels:
        app: telecom-api
    spec:
      containers:
      - name: telecom-api
        image: madhumathib10/telecom-api:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: billing-secret
              key: db-url
