version: '3.9'
services:
  web:
    build: .
    container_name: telecom_api
    environment:
      - DATABASE_URL=postgresql://postgres:Tinku%40123@db:5432/telecom_db
      - JWT_SECRET_KEY=change-this
      - FLASK_APP=run.py
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: telecom_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Tinku%40123
      POSTGRES_DB: telecom_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
