apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: telecom-api-ingress
spec:
  rules:
  - host: billing.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: telecom-api-service
            port:
              number: 80
